version: '3.8'

networks:
  SubredeLocal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.0.3.0/24

  RedePan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.0.2.0/24

services:
  caliandra:
    image: ubuntu:latest
    privileged: true
    command: >
      sh -c "
      apt-get update && apt-get install -y iptables traceroute ufw &&
      echo 1 > /proc/sys/net/ipv4/ip_forward &&
      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
      tail -f /dev/null"
    networks:
      RedePan:
        ipv4_address: 192.0.2.2

  caiman:
    image: ubuntu:latest
    privileged: true
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y iproute2 iptables net-tools ufw curl traceroute iputils-ping &&
      echo 1 > /proc/sys/net/ipv4/ip_forward &&
      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
      ip route del default || true &&
      ip route add default via 192.0.2.2 &&
      ufw enable &&
      tail -f /dev/null"
    networks:
      SubredeLocal:
        ipv4_address: 192.0.3.2
      RedePan:
        ipv4_address: 192.0.2.3

  work:
    image: ubuntu:latest
    privileged: true
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y iproute2 net-tools traceroute iputils-ping sudo curl dnsutils &&
      ip route del default || true &&
      ip route add default via 192.0.3.2 &&
      echo 'Hello from Work' &&
      tail -f /dev/null"
    networks:
      SubredeLocal:
        ipv4_address: 192.0.3.5

  web:
    image: nginx:latest
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "8080:80"
    networks:
      RedePan:
        ipv4_address: 192.0.2.6
