# Networks
networks:
  SubredeLocal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.0.3.0/24
          gateway: 192.0.3.1

  RedePan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.0.2.0/24

services:
  caliandra:
    image: ubuntu:latest
    privileged: true
    volumes:      
      - ./CaliRules/rules.v4:/etc/iptables/rules.v4  # Defina o caminho correto para as regras iptables
      #- ./CaliRules/rules.v4:/etc/iptables/rules.v4  # Mapear o arquivo rules.v4 para o contêiner
    command: ["sh", "-c", "apt-get update && apt-get install -y sudo ufw && sudo ufw --version && sudo ufw default deny incoming && sudo ufw default allow outgoing && sudo chmod +rx /etc/ufw/before.rules && sudo ufw enable && tail -f /dev/null"]
    networks:
      RedePan:
        ipv4_address: 192.0.2.2

  caiman:
    image: ubuntu:latest
    privileged: true
    volumes:      
      - ./CaiRules/rules.v4:/etc/iptables/rules.v4  # Correção do caminho para as regras iptables
    command: ["sh", "-c", "apt-get update && apt-get install -y sudo ufw && ufw --version && ufw default deny incoming && ufw default allow outgoing && chmod +rx /etc/ufw/before.rules && ufw enable && tail -f /dev/null"]
    networks:
      SubredeLocal:
        ipv4_address: 192.0.3.2

  work:
    image: ubuntu:latest
    privileged: true
    command: ["sh", "-c", "echo 'Hello from Work' && tail -f /dev/null"]
    networks:
      SubredeLocal:
        ipv4_address: 192.0.3.5

  web:
    image: nginx:latest
    command: ["nginx", "-g", "daemon off;"]
    ports:
       - "8080:80"
    networks:
      RedePan:
         ipv4_address: 192.0.2.6
