# Use a imagem base do Alpine Linux
FROM alpine:latest

# Instalar netcat
RUN apk add --no-cache netcat-openbsd

# Copiar o script servico.sh para o diretório /usr/local/bin no contêiner
COPY servico.sh /usr/local/bin/servico.sh

# Definir permissões de execução para o script
RUN chmod +x /usr/local/bin/servico.sh

# Executar o script na inicialização do contêiner
ENTRYPOINT ["sh", "-c", "tail -f /dev/null"]
